# Monoboxel configuration file

# DO NOT CHANGE THIS
version: "0.4"

# Multiverse-Core needs some time to initialize
# If you get errors saying Multiverse-Core was not found, but you have installed and enabled it increase this value
# value - time in seconds
world-load-delay: 20


# MonoBoxel will automatically unload unused Boxels
# Specify the time between inactivity checks in seconds
world-unload-period: 60


# Having a lot of Boxels on a server will increase the RAM usage and sever load
# You can specify the maximum global Boxel count here
max-boxel-count: 20


# Set this to true to get better control of which Boxels a player can visit
per-boxel-permissions: false


# Set this to true and MonoBoxel will save the position of a player before he enters a Boxel and will send him back
# to where he was on exit
save-exit-location: true

