name: MonoBoxel
main: com.Monofraps.MonoBoxel.MonoBoxel
version: maven-version-number
load: STARTUP
authors: [Monofraps, MikeMatrix]

commands:
    boxel:
        description: Creates and sends you to your Boxel or the Boxel of <player>
        permissions: monoboxel.boxel
        usage: /<command> <player>
        
    boxelgrp:
        description: Creates and sends you to a group Boxel
        permissions: monoboxel.boxelgrp
        usage: /<command> <boxelname> <password>
        
    boxlookup:
        description: Get the owner of the Boxel your are in
        permissions: monoboxel.boxlookup
        usage: /<command>
       
    boxremove:
        description: Removes the Boxel of the given player (or the own if no parameter is given)
        permissions: monoboxel.boxremove
        usage: /<command> <player>
        
    boxinfo:
        description: Get global MonoBoxel info
        permissions: monoboxel.boxinfo
        usage: /<command>
        
    boxeldbg:
        description: Adds some debug commands
        permissions: monoboxel.debug
        usage: /<command> [dump|version] [boxelToDump]
        
    boxinvite:
        desciption: Invites some player into your Boxel. (in-dev)
        permissions: none yet
        usage: /<command> <player>
        
    boxaccept:
       desciption: Accepts a Boxel invite.
       permissions: none yet
       usage: /<command> <player>
        
    adventure:
        description: This feature is still in development
        permissions: monoboxel.adv
        usage: /<command>